name: "Setup AWS"
description: "Configure AWS credentials using OIDC"
inputs:
  aws-role:
    required: true
    description: "The AWS IAM role to assume"
  aws-region:
    required: false
    description: "AWS region"
    default: "us-east-1"
runs:
  using: "composite"
  steps:
    - name: Retrieving AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role }}
        aws-region: ${{ inputs.aws-region }}